[package]
name = "console-subscriber"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
parking_lot = ["parking_lot_crate", "tracing-subscriber/parking_lot"]

[dependencies]

tokio = { version = "^1.10", features = ["sync", "time", "macros", "tracing"]}
tokio-stream = "0.1"
thread_local = "1.1.4"
console-api = { path = "../console-api", features = ["transport"]}
tonic = { version = "0.5", features = ["transport"] }
tracing-core = "0.1.18"
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.21", default-features = false, features = ["fmt", "registry"] }
futures = { version = "0.3", default-features = false }
hdrhistogram = { version = "7.3.0", default-features = false, features = ["serialization"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# The parking_lot dependency is renamed, because we want our `parking_lot`
# feature to also enable `tracing-subscriber`'s parking_lot feature flag.
parking_lot_crate = { package = "parking_lot", version = "0.11", optional = true }
humantime = "2.1.0"

[dev-dependencies]

tokio = { version = "^1.7", features = ["full", "rt-multi-thread"]}
futures = "0.3"
